/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import entity.Tutor;

/**
 *
 * @author ASUS
 */
public class HomepageTutor extends javax.swing.JFrame {

    private static javax.swing.JFrame frame;
    private Tutor tutor;

    public HomepageTutor() {
        initComponents();
        frame = this;
    }

    public HomepageTutor(Tutor tutor) {
        this();
        this.tutor = tutor;
        
        home.setText(tutor.getNama() + "'s Home");
        namatutor.append(tutor.getNama() + "!");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_seeorder = new javax.swing.JButton();
        home = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        selamatdatang = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        namatutor = new javax.swing.JTextArea();
        btn_logout = new javax.swing.JButton();
        bg_homepage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_seeorder.setBackground(new java.awt.Color(46, 47, 102));
        btn_seeorder.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_seeorder.setForeground(new java.awt.Color(255, 255, 255));
        btn_seeorder.setText("See Order");
        btn_seeorder.setBorder(null);
        btn_seeorder.setBorderPainted(false);
        btn_seeorder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_seeorder.setFocusPainted(false);
        btn_seeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seeorderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_seeorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 140, 40));

        home.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("TUTOR'S HOME");
        home.setToolTipText("");
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, -1, 40));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setFocusable(false);

        selamatdatang.setEditable(false);
        selamatdatang.setBackground(new java.awt.Color(39, 38, 44));
        selamatdatang.setColumns(20);
        selamatdatang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        selamatdatang.setForeground(new java.awt.Color(255, 255, 255));
        selamatdatang.setLineWrap(true);
        selamatdatang.setRows(5);
        selamatdatang.setText("Selamat \nDatang,");
        selamatdatang.setBorder(null);
        selamatdatang.setFocusable(false);
        jScrollPane2.setViewportView(selamatdatang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 170, 110));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);

        namatutor.setEditable(false);
        namatutor.setBackground(new java.awt.Color(39, 38, 44));
        namatutor.setColumns(20);
        namatutor.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        namatutor.setForeground(new java.awt.Color(255, 255, 255));
        namatutor.setLineWrap(true);
        namatutor.setRows(5);
        namatutor.setBorder(null);
        namatutor.setFocusable(false);
        jScrollPane1.setViewportView(namatutor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 270, 50));

        btn_logout.setBackground(new java.awt.Color(0, 102, 0));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Log Out");
        btn_logout.setBorder(null);
        btn_logout.setBorderPainted(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setFocusPainted(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 70, 30));

        bg_homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/HomePage.png"))); // NOI18N
        bg_homepage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(bg_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 870, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seeorderActionPerformed
        // TODO add your handling code here:
        frame.dispose();
        new SeeOrder(tutor).setVisible(true);
    }//GEN-LAST:event_btn_seeorderActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        frame.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_homepage;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_seeorder;
    private javax.swing.JLabel home;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea namatutor;
    private javax.swing.JTextArea selamatdatang;
    // End of variables declaration//GEN-END:variables
}
