/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

/**
 *
 * @author ASUS
 */
public class JanjiWaktu extends javax.swing.JFrame {

    /**
     * Creates new form janjiwaktu
     */
    public JanjiWaktu() {
        initComponents();
       txtTanggal.setBackground(new java.awt.Color(0,0,0,1));
       txtBulan.setBackground(new java.awt.Color(0,0,0,1));
       txtTahun.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tahun = new javax.swing.JComboBox<>();
        Tanggal = new javax.swing.JComboBox<>();
        Bulan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 192, 40, 20));

        Tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalActionPerformed(evt);
            }
        });
        getContentPane().add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 192, 40, 20));

        Bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 192, 40, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/Janji waktu2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bulan;
    private javax.swing.JComboBox<String> Tahun;
    private javax.swing.JComboBox<String> Tanggal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
