/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import db.TutoringDao;
import entity.Murid;
import entity.Tutor;
import entity.Tutoring;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class PembayaranPage extends javax.swing.JFrame {

    private Murid murid;
    private Tutor tutor;
    private String matapelajaran;
    private int jam;
    private Date tanggal;
    private TutoringDao tutoringDao;
    private static javax.swing.JFrame frame;

    public PembayaranPage() {
        initComponents();
        frame = this;
    }

    public PembayaranPage(Murid murid, Tutor tutor, String matapelajaran, int jam, Date tanggal) {
        this();
        this.murid = murid;
        this.tutor = tutor;
        this.matapelajaran = matapelajaran;
        this.jam = jam;
        this.tanggal = tanggal;
        tagihanpembayaran.append("Rp. " + String.valueOf(tutor.getHargaPerJam() * jam));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tagihanpembayaran = new javax.swing.JTextArea();
        btn_paynow = new javax.swing.JButton();
        bg_pembayaran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(85, 85, 85));
        jScrollPane1.setOpaque(false);

        tagihanpembayaran.setBackground(new java.awt.Color(85, 85, 85));
        tagihanpembayaran.setColumns(20);
        tagihanpembayaran.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tagihanpembayaran.setRows(5);
        tagihanpembayaran.setBorder(null);
        tagihanpembayaran.setOpaque(false);
        jScrollPane1.setViewportView(tagihanpembayaran);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 350, 180));

        btn_paynow.setBackground(new java.awt.Color(79, 80, 131));
        btn_paynow.setForeground(new java.awt.Color(255, 255, 255));
        btn_paynow.setText("Pay Now");
        btn_paynow.setBorder(null);
        btn_paynow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paynowActionPerformed(evt);
            }
        });
        getContentPane().add(btn_paynow, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 140, 50));

        bg_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/PembayaranPage.png"))); // NOI18N
        getContentPane().add(bg_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_paynowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paynowActionPerformed
        try {
            // TODO add your handling code here:
            tutoringDao = new TutoringDao();
            Tutoring t = new Tutoring();
            t.setBiaya(jam * tutor.getHargaPerJam());
            t.setJadwal(tanggal);
            t.setJam(jam);
            t.setMatpelPilihan(matapelajaran);
            t.setMurid(murid);
            t.setTutor(tutor);
            tutoringDao.insert(t);
            JOptionPane.showMessageDialog(null, "Pembayaran sukses!",
                    "Selamat!", JOptionPane.OK_OPTION);
            frame.dispose();
            new Homepage(murid).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PembayaranPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_paynowActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_pembayaran;
    private javax.swing.JButton btn_paynow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tagihanpembayaran;
    // End of variables declaration//GEN-END:variables
}
