/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

/**
 *
 * @author ASUS
 */
public class PilihMapelTutorPage extends javax.swing.JFrame {

    /**
     * Creates new form pilihmapeltutorpage
     */
    public PilihMapelTutorPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kimia = new javax.swing.JToggleButton();
        btn_fisika = new javax.swing.JToggleButton();
        btn_ekonomi = new javax.swing.JToggleButton();
        btn_mtk = new javax.swing.JToggleButton();
        btn_indo = new javax.swing.JToggleButton();
        btn_inggris = new javax.swing.JToggleButton();
        bg_PilihMapel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_kimia.setBackground(new java.awt.Color(39, 38, 44));
        btn_kimia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/Group 6.png"))); // NOI18N
        btn_kimia.setBorder(null);
        btn_kimia.setBorderPainted(false);
        btn_kimia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_kimia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kimiaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kimia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, 90));

        btn_fisika.setBackground(new java.awt.Color(39, 38, 44));
        btn_fisika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/Group 7.png"))); // NOI18N
        btn_fisika.setBorderPainted(false);
        btn_fisika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fisikaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_fisika, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 90, 90));

        btn_ekonomi.setBackground(new java.awt.Color(39, 38, 44));
        btn_ekonomi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/Group 8.png"))); // NOI18N
        btn_ekonomi.setBorder(null);
        btn_ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekonomiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ekonomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 90, 90));

        btn_mtk.setBackground(new java.awt.Color(39, 38, 44));
        btn_mtk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/Group 5.png"))); // NOI18N
        btn_mtk.setBorder(null);
        btn_mtk.setBorderPainted(false);
        btn_mtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mtkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 90, 90));

        btn_indo.setBackground(new java.awt.Color(39, 38, 44));
        btn_indo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/Group 10.png"))); // NOI18N
        btn_indo.setBorder(null);
        btn_indo.setBorderPainted(false);
        btn_indo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_indoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_indo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 90, 90));

        btn_inggris.setBackground(new java.awt.Color(39, 38, 44));
        btn_inggris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/Group 9.png"))); // NOI18N
        btn_inggris.setBorder(null);
        btn_inggris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inggrisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_inggris, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 90, 90));

        bg_PilihMapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/Tutorbase.png"))); // NOI18N
        getContentPane().add(bg_PilihMapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kimiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kimiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kimiaActionPerformed

    private void btn_ekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ekonomiActionPerformed

    private void btn_fisikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fisikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fisikaActionPerformed

    private void btn_mtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mtkActionPerformed

    private void btn_indoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_indoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_indoActionPerformed

    private void btn_inggrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inggrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_inggrisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihMapelTutorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihMapelTutorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihMapelTutorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihMapelTutorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihMapelTutorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_PilihMapel;
    private javax.swing.JToggleButton btn_ekonomi;
    private javax.swing.JToggleButton btn_fisika;
    private javax.swing.JToggleButton btn_indo;
    private javax.swing.JToggleButton btn_inggris;
    private javax.swing.JToggleButton btn_kimia;
    private javax.swing.JToggleButton btn_mtk;
    // End of variables declaration//GEN-END:variables
}
