/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import db.TutoringDao;
import entity.Tutor;
import entity.Tutoring;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class SeeOrder extends javax.swing.JFrame {

    private Tutor tutor;
    private List<Tutoring> tutoringList;
    private TutoringDao tutoringDao;
    private static javax.swing.JFrame frame;

    public SeeOrder() {
        initComponents();
        frame = this;
    }

    public SeeOrder(Tutor tutor) {
        this();
        try {
            this.tutor = tutor;

            DefaultTableModel model = new DefaultTableModel();

            tutoringDao = new TutoringDao();
            tutoringList = tutoringDao.getAllTutoringTutor(tutor.getId());

            for (java.lang.reflect.Field field : Tutoring.class.getDeclaredFields()) {
                model.addColumn(field.getName());
            }

            for (Tutoring tutoring : tutoringList) {
                model.addRow(new Object[]{
                    tutoring.getId(),
                    tutoring.getMatpelPilihan(),
                    tutoring.getMurid().getNama(),
                    tutoring.getTutor().getNama(),
                    tutoring.getJam(),
                    tutoring.getJadwal(),
                    tutoring.getBiaya()
                });
            }

            jTable1.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(Riwayat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bg_pembayaran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 680, 320));

        btn_back.setBackground(new java.awt.Color(79, 80, 131));
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setBorder(null);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 140, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Order Tutoring");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        bg_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduBridge_asset/OrderPage.png"))); // NOI18N
        getContentPane().add(bg_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        frame.dispose();
        new HomepageTutor(tutor).setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_pembayaran;
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

